M48
; DRILL file {KiCad 7.0.8} date Sat Jan 27 00:41:16 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-27T00:41:16-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0472
%
G90
G05
T1
X3.4298Y2.32
X3.5298Y2.32
T2
X2.78Y2.49
X2.78Y2.6278
X3.39Y2.63
X3.89Y2.63
T0
M30
